<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <AssemblyName>KoC</AssemblyName>
        <Description>Kick or Clutch Mod</Description>
        <Version>1.16.12</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>latest</LangVersion>
        <RestoreAdditionalProjectSources>
            https://api.nuget.org/v3/index.json;
            https://nuget.bepinex.dev/v3/index.json;
            https://nuget.samboy.dev/v3/index.json
        </RestoreAdditionalProjectSources>
        <RootNamespace>KoC</RootNamespace>
        <Title>Kick or Clutch</Title>
        <Authors>Hi Im Yolo</Authors>
    </PropertyGroup>

    <!-- NuGet Package Dependencies -->
    <ItemGroup>
        <!-- BepInEx Dependencies -->
        <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all"/>
        <PackageReference Include="BepInEx.Core" Version="5.*"/>

        <!-- Additional Plugins and Libraries -->
        <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*"/>
        <PackageReference Include="HtmlAgilityPack" Version="1.11.72"/>
        <PackageReference Include="UnityEngine.Modules" Version="2021.3.33" IncludeAssets="compile"/>
        <PackageReference Include="Fody" Version="6.9.1" PrivateAssets="all"/> <!-- Fody package -->
        <PackageReference Include="Costura.Fody" Version="6.0.0" PrivateAssets="all"/> <!-- Costura package -->
        <PackageReference Include="Zeepkist.GameLibs" Version="16.69.1700"/>
        <PackageReference Include="ZeepSDK" Version="1.38.7"/>
    </ItemGroup>

    <!-- Conditional Dependencies -->
    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all"/>
    </ItemGroup><!-- Post-Build Scripts -->
    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <!-- Delete the plugin directory if it exists -->
        <RemoveDir Directories="C:\Program Files (x86)\Steam\steamapps\common\Zeepkist\BepInEx\plugins\Sideloaded\plugins\$(ProjectName)"/>

        <!-- Create the plugin directory -->
        <MakeDir Directories="C:\Program Files (x86)\Steam\steamapps\common\Zeepkist\BepInEx\plugins\Sideloaded\plugins\$(ProjectName)"/>

        <!-- Copy DLL to the plugin directory -->
        <Exec Command="copy /Y &quot;$(TargetDir)$(ProjectName).dll&quot; &quot;C:\Program Files (x86)\Steam\steamapps\common\Zeepkist\BepInEx\plugins\Sideloaded\plugins\$(ProjectName)\$(ProjectName)-$(Version).dll&quot;"/>
        <!-- Create a zip file from the directory -->
        <Exec Command="powershell -Command &quot;Compress-Archive -Path &quot;&apos;C:\Program Files (x86)\Steam\steamapps\common\Zeepkist\BepInEx\plugins\Sideloaded\Plugins\$(ProjectName)\*&apos;&quot; -DestinationPath &quot;&apos;C:\Program Files (x86)\Steam\steamapps\common\Zeepkist\BepInEx\plugins\Sideloaded\Plugins\$(ProjectName)-$(Version).zip&apos;&quot; -Force&quot;"/>

    </Target>

</Project>